spring:
  jpa:
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:5432/squaders?createDatabaseIfNotExist=true&useSSL=false
    username: postgres
    password: postgres